sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  # 阿里云oss对象存储，图片存储配置
  alioss:
    access-key-id: ${ALI_OSS_KEY_ID}
    access-key-secret: ${ALI_OSS_KEY_SECRET}
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: wscangqiong
